
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Entry eSearchBox;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label lCategory;
	
	private global::Gtk.ComboBox cbCategory;
	
	private global::Gtk.Label lSymbol;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.NodeView tvResult;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("SymbSearch");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.eSearchBox = new global::Gtk.Entry ();
		this.eSearchBox.CanFocus = true;
		this.eSearchBox.Name = "eSearchBox";
		this.eSearchBox.IsEditable = true;
		this.eSearchBox.InvisibleChar = '•';
		this.vbox1.Add (this.eSearchBox);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eSearchBox]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lCategory = new global::Gtk.Label ();
		this.lCategory.Name = "lCategory";
		this.lCategory.LabelProp = global::Mono.Unix.Catalog.GetString ("Category");
		this.hbox1.Add (this.lCategory);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lCategory]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cbCategory = global::Gtk.ComboBox.NewText ();
		this.cbCategory.Name = "cbCategory";
		this.hbox1.Add (this.cbCategory);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbCategory]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lSymbol = new global::Gtk.Label ();
		this.lSymbol.Name = "lSymbol";
		this.lSymbol.Xpad = 10;
		this.lSymbol.LabelProp = global::Mono.Unix.Catalog.GetString ("A");
		this.hbox1.Add (this.lSymbol);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lSymbol]));
		w4.PackType = ((global::Gtk.PackType)(1));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvResult = new global::Gtk.NodeView ();
		this.tvResult.CanFocus = true;
		this.tvResult.Name = "tvResult";
		this.GtkScrolledWindow.Add (this.tvResult);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w7.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.eSearchBox.Changed += new global::System.EventHandler (this.OnESearchBoxChanged);
		this.cbCategory.Changed += new global::System.EventHandler (this.OnCbCategoryChanged);
		this.tvResult.CursorChanged += new global::System.EventHandler (this.OnTvResultCursorChanged);
		this.tvResult.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTvResultRowActivated);
	}
}
